import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    { type: 'category', label: '🖼️ Frontend / Sitios Estáticos', items: [{ type: 'autogenerated', dirName: 'frontend' }] },
    { type: 'category', label: '🚀 Backend / APIs', items: [{ type: 'autogenerated', dirName: 'backend' }] },
    { type: 'category', label: '🗄️ Bases de Datos', items: [{ type: 'autogenerated', dirName: 'bases-de-datos' }] },
    { type: 'category', label: '⚡ Serverless / Edge', items: [{ type: 'autogenerated', dirName: 'serverless' }] },
    { type: 'category', label: '🔧 Full-Stack / Todo-en-uno', items: [{ type: 'autogenerated', dirName: 'fullstack' }] },
    { type: 'category', label: '📦 Almacenamiento de Archivos', items: [{ type: 'autogenerated', dirName: 'almacenamiento' }] },
    { type: 'category', label: '⚙️ CI/CD con GitHub Actions', items: [{ type: 'autogenerated', dirName: 'ci-cd' }] },
    { type: 'category', label: '🌐 Túneles Locales', items: [{ type: 'autogenerated', dirName: 'tuneles-locales' }] },
    { type: 'category', label: '🤖 APIs de IA Gratuitas', items: [{ type: 'autogenerated', dirName: 'ia-gratis' }] },
    { type: 'category', label: '💡 Stacks Recomendados', items: [{ type: 'autogenerated', dirName: 'stacks' }] },
    { type: 'category', label: '🏗️ Proyectos de Práctica', items: [{ type: 'autogenerated', dirName: 'proyectos' }] },
  ],
};

export default sidebars;
